### ISSUE TITLE
Add --debug argument

### ISSUE THREAD

**Issue by cmarqu** [VUnit/vunit#100]
Hi,

I'm looking for a way to selectively print debug output for the simulator setup, like the command line used etc.

There is the `--verbose` argument but that does seems to be reserved to control the verbosity of the simulation run itself. So I'd propose a globally available `--debug` argument.

**Comment by kraigher** [comment]
We already have `--log-level=debug`?

**Comment by cmarqu** [comment]
Ah, indeed, I managed to miss that. Maybe because it doesn't have a help string - could you please add one?

**Comment by kraigher** [comment]
I have already added a help text in the `sphinx`_doc branch were we are working on taking the VUnit documentation to the next level. It will come to master soon.

**Comment by cmarqu** [comment]
Cool, thanks!
