### ISSUE TITLE
[Question] Usage of QuestaSim optimization and Visualiser with VUnit

### ISSUE THREAD

**Issue by SzymonHitachi** [VUnit/vunit#1060]
Hi,
It seems VUnit doesn't support QuestaSim (optimization) and Visualizer out of the box.
How big of an effort would it be to support Those 2 features?

**Comment by LarsAsplund** [comment]
@SzymonHitachi This is something we are currently working on. There  is a prototype  in place but it has some issues. Maybe you can provide some additional input. See #899.
