### ISSUE TITLE
paths/folders generated by vunit are not recognised as valid by modelsim

### ISSUE THREAD

**Issue by swattor** [VUnit/vunit#128]
The default format for a testcase results folder - e.g.

vunit_out/tests/lib.testbench.PARAMETER=X.test1/modelsim/vsim.wlf

isn't valid for modelsim/questa which means you have to navigate to that folder to open it - otherwise you end up with an error "Dataset names can only contain alphanumeric characters or underscores."

Given that a lot of programs tend to use a limited char set for path/filenames perhaps this should be made more friendly?

**Comment by kraigher** [comment]
@swattor When do you get that error? I have used similar path names myself with ModelSim and it worked just fine.

**Comment by kraigher** [comment]
@swattor Is this issue still relevant?

**Comment by LarsAsplund** [comment]
@swattor Is this issue still relevant?

**Comment by LarsAsplund** [comment]
Anyone with access to Questa that has seen this or can recreate this? If not, I will close this issue.
