### ISSUE TITLE
CLI Enhancement Idea: --continue-on-error

### ISSUE THREAD

**Issue by joshrsmith** [VUnit/vunit#140]
When running `--compile`, it might be desirable for VUnit not to exit out when it first encounters an error, but to continue through all steps of the currently executing process.

For example: `python run.py --compile --continue-on-error`

Examples of how this could be helpful:

- Provides a better idea of how many total files in the project compile vs do not compile (due to regressions, incompatibility between different simulators used, etc). This could be used to collect metrics for the code base.
- Allows you to at least partially compile a project, even though some design objects in that library did not compile correctly. This may be perfectly acceptable -- no need for an entire project to compile if you only depend on a few common packages, plus the testbench you are interested in testing.

This option could also apply to normally running VUnit (in simulation mode), but care and thought would need to be given to the case where a newly made change to a design object that your testbench relies on does not get (successfully) recompiled, and you are simulating the old functionality.

**Comment by kraigher** [comment]
There are many good suggestions here. At least adding a flag to continue compiling all files and only stop with errors at the end of the compile session would be reasonable to add. The question is if one should skip compiling files that depend on a file that failed to compile or blindly continue compiling all files. 

The question is also if VUnit should allow simulation to start without a successful compile of all files. Maybe it could detect which test benches depend on files that failed to compile and skip those tests. I think this might not be worth the complexity it is reasonable to not allow simulation of compile failed. Users can easily just comment out the addition of the failing files in their run.py file to go ahead and simulate.
