### ISSUE TITLE
modelsim.vsim_flags appears broken

### ISSUE THREAD

**Issue by swattor** [VUnit/vunit#151]
When I use modelsim.vsim flags to add some options to the sim when the vsim command is constructed the argument i specify has spaces between every letter... e.g.

for this:
vu.set_sim_option("modelsim.vsim_flags", "-voptargs=\"+acc\" -L altera_mf_ver -do sim.do")

the vsim command looks like:
"- v o p t a r g s =  + a c c  - L a l t e r a _ m f _ v e r - d o s i m . d o"

**Comment by kraigher** [comment]
The new option takes a list of strings not a string.

**Comment by kraigher** [comment]
It is to make it consistent with other options

**Comment by swattor** [comment]
Ah I see - thanks for that.
