### ISSUE TITLE
Codec generation does not handle comments in types package

### ISSUE THREAD

**Issue by joshrsmith** [VUnit/vunit#155]
This may be a known issue, but I didn't see the limitation noted in the [documentation](http://vunit.github.io/com/user_guide.html).

For example:
```
package my_msg_types_pkg is

--  type my_type is (something);

  type reset_msg_type_t is (reset);
  type reset_msg_t is record
    msg_type : reset_msg_type_t;
    duration : integer;
  end record reset_msg_t;

end package my_msg_types_pkg;
```

Will end up using `my_type` in codec generation, which is a problem since `my_type` was never actually defined (since it is commented out). This causes the generated codecs package to not compile.

Here is a snippet of what gets generated...

```
...
  function encode (
    constant data : my_type)
    return string;
  alias encode_my_type is encode[my_type return string];
  function decode (
    constant code : string)
    return my_type;
  alias decode_my_type is decode[string return my_type];
  procedure decode (
    constant code   : string;
    variable index : inout positive;
    variable result : out my_type);
  alias decode_my_type is decode[string, positive, my_type];
...
```

**Comment by LarsAsplund** [comment]
I'll add our standard comment removal which ignores anything between `--` and the end of the line. Block comments will not be ignored.
