### ISSUE TITLE
A test name with certain characters in it may create undesirable directory names

### ISSUE THREAD

**Issue by ehliar** [VUnit/vunit#162]
Currently directory names are based directly on the test names which can cause all sorts of troubles if the test names contain for example a "/". It is likely that many test-names that would work on Linux will not be possible to create under Windows, causing a mismatch in functionality between Linux and Windows.

Possible solutions:
1. Disallow such test case names
2. Escape dangerous characters
3. Decouple directory names from test case names

**Comment by kraigher** [comment]
Fixed
