### ISSUE TITLE
Tokens are doubled

### ISSUE THREAD

**Issue by chrgernoe** [VUnit/vunit#201]
The `verilog_parser` argument in the constructor of class `Project` is initialized with an instance of class `VerilogParser`. Already the import of this class causes that the `VerilogParser`/`Tokenizer` constructor is called. However, if an instance of the `VUnit` class is created by the user, the constructor of the `Project` class initializes the `VerilogParser` and hence the `Tokenizer` class again. This causes that all tokens exist twice inside the compiled regular expression object.

**Comment by kraigher** [comment]
It will cause the parser and tokenizer to be created twice, however it will not cause each instance to have twice the token regex in its regular expression. The runtime cost of creating the parser twice is not very high.
