### ISSUE TITLE
Add error on previously defined entities

### ISSUE THREAD

**Issue by gsorrenti** [VUnit/vunit#207]
I suggest to halt the execution on "previously defined entity" warning. It makes no sense to add twice the same file in the same library and it is not acceptable to add two file with the same entity declaration. This type of problems also generate strange and misunderstanding simulator failures.

**Comment by gsorrenti** [comment]
Unfortunately pmi library from Lattice have multiple definition. Now tech library from Lattice compilation fails!

**Comment by gsorrenti** [comment]
Maybe I was  too much reckless

**Comment by kraigher** [comment]
@gsorrenti So maybe we revert this back to a warning again? Any other suggestion.

**Comment by gsorrenti** [comment]
Yes, please. Sorry again

**Comment by kraigher** [comment]
I made it a warning again now.
