### ISSUE TITLE
Modelsim startup.do

### ISSUE THREAD

**Issue by drizzd** [VUnit/vunit#223]
I would like to do something like `vsim -gui -do "source startup.do" lib.design`, where startup.do will typically do stuff like adding signals to the waveform viewer. Is this possible with VUnit?

I am trying to use `VUnit.set_sim_option("modelsim.vsim_flags.gui", ["-do", "\"source startup.do\""])`, but I get a warning `Ignoring nested -do argument: "source startup.do"` and the script is not executed. I think the reason is that VUnit does `vsim -gui -do "do gui_load.do"`, and gui_load.do in turn calls vsim. Together that amounts to `vsim -gui -do "vsim -do \"source_startup.do\" lib.design"`, i.e. a "nested do"

I guess I could teach VUnit to run `vsim -gui -do "source startup.do" lib.design` with all the appropriate options, but then I cannot run vunit_run in the GUI any more, right?

**Comment by kraigher** [comment]
We could add a new simulation option such as "modelsim.startup_file.gui" that allows specifying a file that will be sourced after loading the top level in vunit_load.

We could also add a comment pragma to allow setting such a file from within a test bench to avoid having to go through run.py.

This would cover the use case that you want to have a waveform configuration script always run when opening a test bench in gui mode.

**Comment by drizzd** [comment]
Sounds good to me. I don't think I would be using the comment pragma, though.

**Comment by kraigher** [comment]
You can check out the issue_223 branch and see if the feature is to your liking.

**Comment by kraigher** [comment]
I also added a TCL prodecure exposed in the GUI named `vunit_startup` such that you can re-run your custom startup file in the GUI. Might be useful when developing the startup file and adding signals to it etc.

**Comment by kraigher** [comment]
I do not now if "startup_file" is the best name for this. Anyone can think of something better? Otherwise I might let it stick.

**Comment by joshrsmith** [comment]
Some other possibilities: init_script, custom_init_script

**Comment by kraigher** [comment]
I decided to call it `init_file`. It is on master now.

**Comment by drizzd** [comment]
Tested here and works like a charm. It is very reassuring that even feature requests are implemented so quickly. Thank you!

Here is a possibly helpful observation for future users. The working directory in init_file is different from the command line working directory. In order to run scripts which reside in the directory that also contains init_file, resolve the path like this:

    # Call wave.do from init_file.do
    do [file join [file dirname [info script]] wave.do]
