### ISSUE TITLE
Modelsim coverage not working

### ISSUE THREAD

**Issue by cmon1** [VUnit/vunit#224]
When starting VUnit with --coverage option using Modelsim a KeyError occur in modelsim_interface.py:

>   File "C:\tools\Python27\lib\site-packages\vunit\modelsim_interface.py", line 247, in _create_load_function
>      HASH_TO_TEST_NAME[os.path.basename(os.path.dirname(output_path))],
>  KeyError: 'test_output'

I got this fixed by exchanging _output_path_ with _coverage_file_ in line 247 of modelsim_interface.py.

**Comment by kraigher** [comment]
Yes this has slipped in during a refactor. Unfortunately we have no automated test for this due to lack of license. I will fix it.

**Comment by cmon1** [comment]
Thank you!

**Comment by kraigher** [comment]
This is fixed on master now.
