### ISSUE TITLE
Add code coverage support for Aldec Riviera-Pro

### ISSUE THREAD

**Issue by noasic** [VUnit/vunit#225]
Code coverage is currently supported only for ModelSim. I'd like to have it supported in Riviera-Pro too.

**Comment by bbmag-bard** [comment]
That would be great! I'm also using the Riviera-Pro simulator and would be looking forward to using this feature.

**Comment by noasic** [comment]
I've added experimental support to Riviera-Pro code coverage on a local branch but I don't have permission to push that branch to the Github repository:

> remote: Permission to VUnit/vunit.git denied to noasic.
> fatal: unable to access 'https://github.com/VUnit/vunit.git/': The requested URL returned error: 403

How am I supposed to proceed?

**Comment by kraigher** [comment]
@noasic The process is: You do a "pull request" in the GitHub web GUI from your fork to the VUnit repo. Then you pass all automated tests and fix our comments on your commits and then we press the merge button.
