### ISSUE TITLE
Logging vunit output

### ISSUE THREAD

**Issue by asicnet** [VUnit/vunit#258]
Hi
Is it possible to configure vunit, that all outputs on the terminal or cmd window are logged to a file like run.log without to call the cmd.exe and then run.py>log (stderr and stdout)
Best regards

**Comment by kraigher** [comment]
I do not think doing it inside the VUnit library is a good architecture. VUnit is just a Python library that the user uses in his run.py file. This is probably better to do it in the shell outside of VUnit, you can always make a wrapper script that runs the run.py file if this is common. For must use cases VUnit also already saves the test output data to files in each test folder as well as in the xunit.xml report file. Also on Jenkins all output is automatically logged.
