### ISSUE TITLE
Launch Vunit tests in the loop

### ISSUE THREAD

**Issue by alinaivanovaoff** [VUnit/vunit#308]
Is it possible to launch Vunit tests in the loop? I mean, if tests finished successfully - just launch again, if some of the tests failed - exit?

**Comment by sthenc** [comment]
If it is the same testcases, why would you do that?

**Comment by alinaivanovaoff** [comment]
No, it’s not the same tests. Every time will load new configuration. In the python script will generate new set of parameters and launch VUnit tests.

**Comment by alinaivanovaoff** [comment]
Also, it allows to test with different random seeds. So It allows to achieve good code coverage.

**Comment by kraigher** [comment]
@alinaivanovaoff Seems like your use case is covered by adding many test configurations using the add_config method. Example: http://vunit.github.io/python_interface.html#example
It allow creating named runs of the same test bench using different configuration of simulator flags, generics/parameters, post_check/pre_config etc.

**Comment by alinaivanovaoff** [comment]
Unfortunately it’s not suitable for my case, because I have so much configuration and we don’t plane generate it. If I can launch VUnit in the loop I can combine VUnit run.py script with my others and l can lunch so much configurations or random seed as I want.

**Comment by kraigher** [comment]
Is the loop infinite? If you want to run 1000 iterations you can call add_config 1000 times. Also you can always run the run.py file itself in a loop.  Or you can loop at RTL-level instead. There are many options.

**Comment by alinaivanovaoff** [comment]
Ok, I’ll try
