### ISSUE TITLE
add_source_file : Add argument to disable code coverage for selected file/files

### ISSUE THREAD

**Issue by krishnan-gopal** [VUnit/vunit#330]
This is particularly very useful for bigger testbenches, where code coverage doesnt need to be collected (for example UVM-based TBs).  By specifying which files need to be enabled/disabled for code coverage, the simulation performance can be drastically improved.

**Comment by kraigher** [comment]
Do you need to selectively control type of coverage for individual files or just on/off with respect to the type of coverage provided by the `--coverage` argument.

**Comment by krishnan-gopal** [comment]
It's enough to turn off for a file/ files so that --coverage doesn't have any effect on that file. Basically the result is that the selected file/files are always compiled without coverage while the other files are dependent on the --coverage argument
