### ISSUE TITLE
log when test passed

### ISSUE THREAD

**Issue by slaweksiluk** [VUnit/vunit#362]
I have question regarding logging. Is it possible to print something (for example with info() ) to terminal when test is passed?. I can use '-v' option but then it also prints some mess from IP Cores.

**Comment by kraigher** [comment]
It is not possible. You can log to a file if you want to isolate logging from normal stdout.

**Comment by 1138-4EB** [comment]
A combination of logging to a file and `tail -f` might achieve the same output?
