### ISSUE TITLE
handle sync in axi_stream_slave

### ISSUE THREAD

**Issue by hughjackson** [VUnit/vunit#368]
It would be useful to be able handle sync messages (specifically wait for time) in axi_stream_slave verification component (in the same way that axi_stream_master does). Adding either `handle_sync_message(net, msg_type, msg);` or `handle_wait_for_time(net, msg_type, msg);` should be all that needs doing.

Along with this change would be the addition of the as_sync function for the slave type.

**Comment by kraigher** [comment]
Good enhancement, will you make a pull request?

**Comment by hughjackson** [comment]
Thanks, pull request opened here: https://github.com/VUnit/vunit/pull/371
