### ISSUE TITLE
Detailed XUnit failure message

### ISSUE THREAD

**Issue by crdavis12** [VUnit/vunit#384]
It would be nice to have a more detailed failure message in the XUnit output file. Currently the message is either just "Failed" or "Skipped" (set in test_report.py). Initial thoughts are to put in the last few lines of the system output, but I'd be interested in other opinions.

Use case: I have VUnit automated with Bamboo. When a test case fails, the failure message shows up on the test results screen. It would be nice to not have to dig into the log for every failure.

![20180827_bamboo_vunit_failure](https://user-images.githubusercontent.com/30438053/44662678-0118f400-a9fe-11e8-8cf7-f4cec6b70825.PNG)

**Comment by kraigher** [comment]
Full output for each test is added to the XML file. Open it and see yourself. This must be a Bamboo limitation. In Jenkins I can click the test and see full output.

**Comment by crdavis12** [comment]
Bamboo does not show the full output. It just pulls the text out of the failure element, message attribute. I do see it in the XML file when running locally.

**Comment by kraigher** [comment]
You could try to report this to Bamboo as a bug or missing feature?

**Comment by crdavis12** [comment]
I could. Bamboo aside, it seems like having the details under the failure message would make more sense though. Would that cause issues somewhere else?

**Comment by kraigher** [comment]
Maybe the current contents of `<system-out>` can be put as text inside `<failure>` tag when the test fails and kept in `<system_out>` when the test passes. Could you experiment with of Bamboo reacts to text inside the `<failure>` tag?

Unfortunately there is no formal standard for JUnit XML and various implementations handle it differently. Ideally we can find a format that works everywhere. In failure of that we might need to add a `--xunit-xml-format` flag that can be either `jenkins|bamboo` with `jenkins` being the default for backwards compatability.

**Comment by crdavis12** [comment]
I like that idea. Also agree with the idea of trying to find a format that works everywhere.

Looks like Bamboo does display text inside of the <failure> tag. The message attribute is shown first, followed by a line break and then the text inside the tag.

**Comment by kraigher** [comment]
I think system-out should always contain the output regardless of failure like today but the failure tag should get a copy of system-out in case of failure. This is to make it backwards compatible in the case someone uses system-out. 

We need check how Jenkins reacts to this first though.

**Comment by kraigher** [comment]
Will you create a pull request?

**Comment by crdavis12** [comment]
Done: https://github.com/VUnit/vunit/pull/386

**Comment by kraigher** [comment]
Seems this is a long standing issue with Bamboo: https://community.atlassian.com/t5/Bamboo-questions/junit-parser-doesn-t-parse-quot-system-out-quot-element-in-test/qaq-p/345459

In Jenkins this solution is not ideal since Jenkins will display both the `<failure>` text as well as the `<system-out>` text which will cause duplicate output. Unfortunately there is thus no good solution that works for both Jenkins and Bamboo simultaneously so this has to be configurable. I can see the potential of adding `--xunit-xml-format' argument which can be `jenkins`(default) or `bamboo` to select the behavior.

**Comment by crdavis12** [comment]
Another non-ideal option is to remove the text from <system-out>, but that may cause issues if someone is depending on text in that field during a failure.

**Comment by kraigher** [comment]
I think changing system-out is not ideal and probably break backwards compatibility for someone. Also logically the system-out is still the system-out even in failure. It think it has to be a bamboo specific work arround that is opt in.

**Comment by crdavis12** [comment]
That's fair. I will take a stab at implementing the `--xunit-xml-format` argument.
