### ISSUE TITLE
Deallocate memory

### ISSUE THREAD

**Issue by eschmidscs** [VUnit/vunit#397]
Hi

Is there a way to deallocate memory blocks?
I couldn't find a function for this in memory_pkg.

Thanks and best regards,
emanuel

**Comment by kraigher** [comment]
Not yet but it can easily be added. Now you can always clear the entire memory between iterations if you run many test iterations.

**Comment by eschmidscs** [comment]
Thanks for the answer.
I'm closing this - I was more afraid that I miss something.
