### ISSUE TITLE
tb_path returns path to preprocessed directory

### ISSUE THREAD

**Issue by felixn** [VUnit/vunit#402]
I'm using `tb_path(runner_cfg)` in a testbench to get the path of the current testbench, and to read stimuli files from that folder.

If I turn on check/location preprocessing with `ui.enable_check_preprocessing()` / `ui.enable_location_preprocessing()`, tb_path returns a path inside `vunit_out/preprocessed/`.

This doesn't work, because this directory doesn't contain the stimuli files.
Is there a way to get the original path containing the testbench that works regardless whether preprocessing is turned on or not?

**Comment by kraigher** [comment]
You can always create your own path to the test data in Python and set another generic which will work regardless of preprocessing. Anyway we could fix such that the tb_path generic works regardless of preprocessing as well.

**Comment by kraigher** [comment]
I pushed a commit to master which makes tb_path work in combination with preprocessing.
