### ISSUE TITLE
modelsim gui merge coverage

### ISSUE THREAD

**Issue by imd1** [VUnit/vunit#427]
After running a test using the Modelsim GUI, the merge coverage fails on line 336 of modelsim_interface.py as "AttributeError: 'NoneType` object has no attribute `teardown`.

It appears that the Modelsim version of merge_coverage() differs from the Rivierapro version (lines 333-335 of riverapro_interface.py) in that it does not have an "if not NONE" protection 

```
        if self._persistent_shell is not None:
            # Teardown to ensure acdb file was written.
            self._persistent_shell.teardown()
```

My question is whether this protection should also be added to the Modelsim version?

**Comment by kraigher** [comment]
Yes this was recently fixed in rivierapro and the same fix should be applied in modelsim.py? Could you make a PR?

**Comment by imd1** [comment]
Done
