### ISSUE TITLE
Add code coverage support ActiveHDL

### ISSUE THREAD

**Issue by vmfox** [VUnit/vunit#460]
Following my recent chat on Gitter regarding cove coverage support for ActiveHDL I would like to contribute the changes that would allow this to happen. I have a working version of the relevant .py file which was tested on a real project, and I can prove that the modification generate coverage files for each unit and final merged coverage file. The run.py interface is identical to the already existing one and hence would not require any changes.

I am not able to branch off to add this feature so it would be great if someone could assist me with it.

**Comment by kraigher** [comment]
The workflow of creating PRs is explained by github here: https://help.github.com/en/articles/creating-a-pull-request-from-a-fork

**Comment by vmfox** [comment]
Tack så mycket.

**Comment by kraigher** [comment]
I guess we can close this issue as the PR is merged.
