### ISSUE TITLE
Unism Library not found

### ISSUE THREAD

**Issue by dsp20** [VUnit/vunit#489]
I am getting unisim library related error. I have compiled Xilinx IPs for Questasim. Still, compilation giving an error. What could be the solution for this?
![Capture](https://user-images.githubusercontent.com/46738970/56793220-18c4a880-6829-11e9-9d63-3309841fccf9.PNG)

**Comment by kraigher** [comment]
The only reason I can think of is that the unisim library is not compiled and added to the project.

**Comment by dsp20** [comment]
I have modified modelsim.ini file and now able to see all library files in Questasim. Please see attached image 
![Questa](https://user-images.githubusercontent.com/46738970/57077271-3dc58980-6d09-11e9-8b18-9e2e27868a14.PNG)
In this image we can see "proc_sys_reset_v5_0_13" library is added in Questasim. But while compiling  project from Vunit it is giving an error for "proc_sys_reset_v5_0_13". Please see attached command prompt image
![Vunit](https://user-images.githubusercontent.com/46738970/57077410-9e54c680-6d09-11e9-9213-3faa1cdac757.PNG)

Do I need to add any script in run.py related to proc_sys_reset_v5_0_13 library?

**Comment by LarsAsplund** [comment]
@dsp20 Can this also be closed?

**Comment by dsp20** [comment]
Yes. This can be closed
