### ISSUE TITLE
How to pass >32 bit variables from python script to DUT

### ISSUE THREAD

**Issue by marph91** [VUnit/vunit#490]
I have a DUT with an input of type `std_logic_vector(127 downto 0)`. In a python script the value is generated and has to be passed to the DUT. My current approach is to split it in four 32 bit integer and save to the csv file, only to reassemble it later to the 128 bit vector again. What is the best practice for this scenario?

**Comment by LarsAsplund** [comment]
You can pass it as a string generic. Have a look at #419.
