### ISSUE TITLE
Searching the docs doesn't work

### ISSUE THREAD

**Issue by Sturla22** [VUnit/vunit#713]
Any search term in https://vunit.github.io/search.html will not return a result, for example: https://vunit.github.io/search.html?q=VUnit&check_keywords=yes&area=default

It would completely change how I browse the docs if this feature worked.

**Comment by LarsAsplund** [comment]
Googling reveals that many are having this problem lately. A number of workarounds have been suggested. We'll have to investigate which one to go for. Any ideas @eine ?

**Comment by LarsAsplund** [comment]
Reverting to Sphinx 3.3.1 works when building locally. I will push that as a workaround.

**Comment by LarsAsplund** [comment]
Up and running again

**Comment by Sturla22** [comment]
Awesome, thank you for the great work you guys do with VUnit!
