### ISSUE TITLE
Possible to include/compile MicroSemi IPs?

### ISSUE THREAD

**Issue by sibeov** [VUnit/vunit#787]
Hello.

Has anyone had any experience with compiling MicroSemi IPs? 
If this is not the right place for questions then please redirect me.

Kind Regards

**Comment by nfrancque** [comment]
@sibeov There was some gitter discussion about this [here](https://gitter.im/VUnit/vunit?at=60f13fc1d2556414f568eec1), you can ask more there if needed.  In general, you can do whatever you are already doing for the microsemi IP, and then inform vunit that the compile artifacts are there.

**Comment by LarsAsplund** [comment]
@sibeov I also recommend the gitter channel as the better forum for such a discussion. There you can find people with such experiences.
