### ISSUE TITLE
Pure Python VUnit version

### ISSUE THREAD

**Issue by qarlosalberto** [VUnit/vunit#873]
I would like to use in TerosHDL VUnit with pyscript (https://github.com/pyscript/pyscript). But it fails because there is no VUnit pure Python version in PIP. Could it be possible to add it? https://pyodide.org/en/stable/usage/faq.html#micropip-can-t-find-a-pure-python-wheel

**Comment by qarlosalberto** [comment]
Added request: https://github.com/pyodide/pyodide/issues/3245

**Comment by LarsAsplund** [comment]
@qarlosalberto Will you still need a wheel on PyPi? We had an discussion about this on gitter and I think that will be added shortly

**Comment by qarlosalberto** [comment]
Yes, I need. For now I have built it manually.

**Comment by umarcor** [comment]
Was this solved or shall we reopen it?
