### ISSUE TITLE
42 tests fail

### ISSUE THREAD

**Issue by yurivict** [VUnit/vunit#941]
[log](https://people.freebsd.org/~yuri/vunit-hdl-4.7.0-test.txt)

Version: 4.7.0
python-3.9
ghdl-3.0.0
OS: FreeBSD 13.2

**Comment by umarcor** [comment]
Did you install VUnit? Errors are: `ModuleNotFoundError: No module named 'vunit'`.

You need to install VUnit locally (you can use a venv, tox, nox, etc.) because those tests do use VUnit itself.

**Comment by LarsAsplund** [comment]
@yurivict Any updates on this? Still a problem?

**Comment by PhilipBotha** [comment]
I had to add the path to the directory where `vunit` is installed to `PYTHONPATH`. This was WSL.

**Comment by yurivict** [comment]
```vunit``` wasn't available for some tests.
When I added the path to PYTHONPATH - the problem disappeared.

Thank you!
