### ISSUE TITLE
Can't seem to run Vopt separately in Vunit. This is needed for new workflow with Questa Visualizer.

### ISSUE THREAD

**Issue by imsahan** [VUnit/vunit#950]
I want to run Vunit with Questa Visualizer. To invoke visualizer, you need to run Vopt first and then Vsim. I don't see a way to do this with Vunit. Is there a fix that can be made to allow calling Vopt separately?

See pictures below for more details on Visualizer:
![1](https://github.com/VUnit/vunit/assets/139786369/2501ad0c-b0be-415e-a290-1602039b06f0)
![2](https://github.com/VUnit/vunit/assets/139786369/2baf2138-88b6-4ca1-8f9c-25c379209da4)

**Comment by LarsAsplund** [comment]
@imsahan I think this issue is covered by #899. Agree?

**Comment by imsahan** [comment]
Ah yes that is correct. Should I close my issue?
