### ISSUE TITLE
tb_filter 

### ISSUE THREAD

**Issue by vermaete** [VUnit/vunit#99]
A warning when no testbench that match the tb_filter (^tb_.* | *._tb$) is found would be nice.
Now we saw a message that no testcases where found with the './run.py --list' cmd.

**Comment by kraigher** [comment]
I agree a warning is reasonable in all cases except when invoking VUnit with `--compile` option. If not just to help users remember the criteria for what defines a test bench.

**Comment by kraigher** [comment]
Implemented and released in v0.51.2.
