### ISSUE TITLE
News fragments of the contributions/modifications done in the last 7 months

### ISSUE THREAD

**Issue by umarcor** [VUnit/vunit#997]
The last news fragment was added/edited 7 months ago: https://github.com/VUnit/vunit/tree/master/docs/news.d.
Since then, ~30 commits were pushed to branch `master`, without editing/adding corresponding fragments.
Therefore, those enhancements/fixes are not shown in http://vunit.github.io/release_notes.html#next.
Before tagging the next release, all the missing fragments need to be added.

@LarsAsplund, @bewimm, @abaebae, @oscargus, @kraigher, @awillenbuecher-xq-tec, @g0t00, @LukasVik, according to https://github.com/VUnit/vunit/commits/master/ you all contributed at least one commit in this period but did not add a news fragment. Please, evaluate whether you should create a PR to add it/them, or if not necessary, reply to this issue making it explicit that the changes you contributed are not relevant enough to be written down in the release notes.

- [X] #799
- [X] #956
- [x] #965
- [x] #967
- [x] #971
- [x] #972
- [X] #989
- [X] #992
- [X] #994
- [x] #889
- [x] #924
- [x] #981
- [x] #983
- [x] #993
- [x] #996

**Comment by LukasVik** [comment]
Added for the ones that I was involved in: https://github.com/VUnit/vunit/pull/1000
